- name: Hello Block 1
  hosts: all
  vars_files: []

  roles: []

  tasks:
    - name: ping
      ansible.builtin.ping: 

    - name: Clone isamples-ansible repo
      git:
        repo: https://github.com/isamplesorg/isamples-ansible.git
        dest: /home/ubuntu/isamples-ansible

    - name: Install poetry
      shell: curl -sSL https://install.python-poetry.org | python3 -
      args:
        creates: /root/.poetry/bin/poetry

    - name: Run poetry shell and poetry install
      shell: |
        source ~/.bashrc
        /home/ubuntu/.local/bin/poetry install
      args:
        executable: /bin/bash
        chdir: /home/ubuntu/isamples-ansible

    # install nginx and certbot
    - name: Install nginx
      apt:
        name:
          - nginx
      become: yes

    - name: Install certbot
      apt:
        name:
          - python3-certbot-nginx
      become: yes

    - name: stop for now
      meta: end_play
      when: true

    - name: Lay down default nginx config before running certbot
      template:
        src: ./isamples-ina-box-nginx.j2
        dest: /etc/nginx/sites-enabled/default

    - name: Set up the certbot config in nginx
      shell: "certbot --nginx -d {{ hostname }} -m {{ certbot_email }} -n --agree-tos --redirect"
      become: yes

    - name: Start nginx
      service:
        name: nginx
        state: started

    # install docker and docker-compose
    - name: Install Docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Install Docker and Docker compose
      shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && mkdir -p /usr/local/lib/docker/cli-plugins &&  curl -SL